//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsPrecioTasaEquivalente.wsprecio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsprecio.IWSCalculoPrecioTasaEquivalente")]
    public interface IWSCalculoPrecioTasaEquivalente {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WSCalculoPrecioTasaEquivalenteIntf-IWSCalculoPrecioTasaEquivalente#CalcularPr" +
            "ecioTasaEquivalente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteResponse CalcularPrecioTasaEquivalente(WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:WSCalculoPrecioTasaEquivalenteIntf-IWSCalculoPrecioTasaEquivalente#CalcularPr" +
            "ecioTasaEquivalente", ReplyAction="*")]
        System.Threading.Tasks.Task<WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteResponse> CalcularPrecioTasaEquivalenteAsync(WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WSCalculoPrecioTasaEquivalenteIntf")]
    public partial class TCalculoPrecioTasa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string colaRespuestaField;
        
        private int timeOutField;
        
        private string mercadoField;
        
        private string tipoIdTituloField;
        
        private string idTituloField;
        
        private string tipoDeNegociacionField;
        
        private int plazoDeIdaField;
        
        private int plazoDeVueltaField;
        
        private double precioOTasaField;
        
        private string monedaField;
        
        private string enteLiquidadorField;
        
        private System.DateTime fechaDeProcesoField;
        
        private System.DateTime tNE_FechaDeEmisionField;
        
        private System.DateTime tNE_FechaDeVencimientoField;
        
        private string tNE_PeriodicidadDePagoField;
        
        private string tNE_ModalidadDePagoField;
        
        private string tNE_PeriodicidadDeReinversionField;
        
        private string tNE_ModalidadDeReinversionField;
        
        private double tNE_TasaFacialField;
        
        private double tNE_PremioField;
        
        /// <remarks/>
        public string ColaRespuesta {
            get {
                return this.colaRespuestaField;
            }
            set {
                this.colaRespuestaField = value;
                this.RaisePropertyChanged("ColaRespuesta");
            }
        }
        
        /// <remarks/>
        public int TimeOut {
            get {
                return this.timeOutField;
            }
            set {
                this.timeOutField = value;
                this.RaisePropertyChanged("TimeOut");
            }
        }
        
        /// <remarks/>
        public string Mercado {
            get {
                return this.mercadoField;
            }
            set {
                this.mercadoField = value;
                this.RaisePropertyChanged("Mercado");
            }
        }
        
        /// <remarks/>
        public string TipoIdTitulo {
            get {
                return this.tipoIdTituloField;
            }
            set {
                this.tipoIdTituloField = value;
                this.RaisePropertyChanged("TipoIdTitulo");
            }
        }
        
        /// <remarks/>
        public string IdTitulo {
            get {
                return this.idTituloField;
            }
            set {
                this.idTituloField = value;
                this.RaisePropertyChanged("IdTitulo");
            }
        }
        
        /// <remarks/>
        public string TipoDeNegociacion {
            get {
                return this.tipoDeNegociacionField;
            }
            set {
                this.tipoDeNegociacionField = value;
                this.RaisePropertyChanged("TipoDeNegociacion");
            }
        }
        
        /// <remarks/>
        public int PlazoDeIda {
            get {
                return this.plazoDeIdaField;
            }
            set {
                this.plazoDeIdaField = value;
                this.RaisePropertyChanged("PlazoDeIda");
            }
        }
        
        /// <remarks/>
        public int PlazoDeVuelta {
            get {
                return this.plazoDeVueltaField;
            }
            set {
                this.plazoDeVueltaField = value;
                this.RaisePropertyChanged("PlazoDeVuelta");
            }
        }
        
        /// <remarks/>
        public double PrecioOTasa {
            get {
                return this.precioOTasaField;
            }
            set {
                this.precioOTasaField = value;
                this.RaisePropertyChanged("PrecioOTasa");
            }
        }
        
        /// <remarks/>
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <remarks/>
        public string EnteLiquidador {
            get {
                return this.enteLiquidadorField;
            }
            set {
                this.enteLiquidadorField = value;
                this.RaisePropertyChanged("EnteLiquidador");
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaDeProceso {
            get {
                return this.fechaDeProcesoField;
            }
            set {
                this.fechaDeProcesoField = value;
                this.RaisePropertyChanged("FechaDeProceso");
            }
        }
        
        /// <remarks/>
        public System.DateTime TNE_FechaDeEmision {
            get {
                return this.tNE_FechaDeEmisionField;
            }
            set {
                this.tNE_FechaDeEmisionField = value;
                this.RaisePropertyChanged("TNE_FechaDeEmision");
            }
        }
        
        /// <remarks/>
        public System.DateTime TNE_FechaDeVencimiento {
            get {
                return this.tNE_FechaDeVencimientoField;
            }
            set {
                this.tNE_FechaDeVencimientoField = value;
                this.RaisePropertyChanged("TNE_FechaDeVencimiento");
            }
        }
        
        /// <remarks/>
        public string TNE_PeriodicidadDePago {
            get {
                return this.tNE_PeriodicidadDePagoField;
            }
            set {
                this.tNE_PeriodicidadDePagoField = value;
                this.RaisePropertyChanged("TNE_PeriodicidadDePago");
            }
        }
        
        /// <remarks/>
        public string TNE_ModalidadDePago {
            get {
                return this.tNE_ModalidadDePagoField;
            }
            set {
                this.tNE_ModalidadDePagoField = value;
                this.RaisePropertyChanged("TNE_ModalidadDePago");
            }
        }
        
        /// <remarks/>
        public string TNE_PeriodicidadDeReinversion {
            get {
                return this.tNE_PeriodicidadDeReinversionField;
            }
            set {
                this.tNE_PeriodicidadDeReinversionField = value;
                this.RaisePropertyChanged("TNE_PeriodicidadDeReinversion");
            }
        }
        
        /// <remarks/>
        public string TNE_ModalidadDeReinversion {
            get {
                return this.tNE_ModalidadDeReinversionField;
            }
            set {
                this.tNE_ModalidadDeReinversionField = value;
                this.RaisePropertyChanged("TNE_ModalidadDeReinversion");
            }
        }
        
        /// <remarks/>
        public double TNE_TasaFacial {
            get {
                return this.tNE_TasaFacialField;
            }
            set {
                this.tNE_TasaFacialField = value;
                this.RaisePropertyChanged("TNE_TasaFacial");
            }
        }
        
        /// <remarks/>
        public double TNE_Premio {
            get {
                return this.tNE_PremioField;
            }
            set {
                this.tNE_PremioField = value;
                this.RaisePropertyChanged("TNE_Premio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WSCalculoPrecioTasaEquivalenteIntf")]
    public partial class TWSMensajeRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcularPrecioTasaEquivalente", WrapperNamespace="urn:WSCalculoPrecioTasaEquivalenteIntf-IWSCalculoPrecioTasaEquivalente", IsWrapped=true)]
    public partial class CalcularPrecioTasaEquivalenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WsPrecioTasaEquivalente.wsprecio.TCalculoPrecioTasa oCalculoPrecioTasa;
        
        public CalcularPrecioTasaEquivalenteRequest() {
        }
        
        public CalcularPrecioTasaEquivalenteRequest(WsPrecioTasaEquivalente.wsprecio.TCalculoPrecioTasa oCalculoPrecioTasa) {
            this.oCalculoPrecioTasa = oCalculoPrecioTasa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcularPrecioTasaEquivalenteResponse", WrapperNamespace="urn:WSCalculoPrecioTasaEquivalenteIntf-IWSCalculoPrecioTasaEquivalente", IsWrapped=true)]
    public partial class CalcularPrecioTasaEquivalenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Moneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double PrecioTasaEquivalente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public WsPrecioTasaEquivalente.wsprecio.TWSMensajeRespuesta @return;
        
        public CalcularPrecioTasaEquivalenteResponse() {
        }
        
        public CalcularPrecioTasaEquivalenteResponse(string Moneda, double PrecioTasaEquivalente, WsPrecioTasaEquivalente.wsprecio.TWSMensajeRespuesta @return) {
            this.Moneda = Moneda;
            this.PrecioTasaEquivalente = PrecioTasaEquivalente;
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSCalculoPrecioTasaEquivalenteChannel : WsPrecioTasaEquivalente.wsprecio.IWSCalculoPrecioTasaEquivalente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCalculoPrecioTasaEquivalenteClient : System.ServiceModel.ClientBase<WsPrecioTasaEquivalente.wsprecio.IWSCalculoPrecioTasaEquivalente>, WsPrecioTasaEquivalente.wsprecio.IWSCalculoPrecioTasaEquivalente {
        
        public WSCalculoPrecioTasaEquivalenteClient() {
        }
        
        public WSCalculoPrecioTasaEquivalenteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCalculoPrecioTasaEquivalenteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCalculoPrecioTasaEquivalenteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCalculoPrecioTasaEquivalenteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteResponse WsPrecioTasaEquivalente.wsprecio.IWSCalculoPrecioTasaEquivalente.CalcularPrecioTasaEquivalente(WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteRequest request) {
            return base.Channel.CalcularPrecioTasaEquivalente(request);
        }
        
        public string CalcularPrecioTasaEquivalente(WsPrecioTasaEquivalente.wsprecio.TCalculoPrecioTasa oCalculoPrecioTasa, out double PrecioTasaEquivalente, out WsPrecioTasaEquivalente.wsprecio.TWSMensajeRespuesta @return) {
            WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteRequest inValue = new WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteRequest();
            inValue.oCalculoPrecioTasa = oCalculoPrecioTasa;
            WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteResponse retVal = ((WsPrecioTasaEquivalente.wsprecio.IWSCalculoPrecioTasaEquivalente)(this)).CalcularPrecioTasaEquivalente(inValue);
            PrecioTasaEquivalente = retVal.PrecioTasaEquivalente;
            @return = retVal.@return;
            return retVal.Moneda;
        }
        
        public System.Threading.Tasks.Task<WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteResponse> CalcularPrecioTasaEquivalenteAsync(WsPrecioTasaEquivalente.wsprecio.CalcularPrecioTasaEquivalenteRequest request) {
            return base.Channel.CalcularPrecioTasaEquivalenteAsync(request);
        }
    }
}
